version: '2'

services:

  ##
  # PHP Processing.
  #
  train-phpfpm:
    build:
        context: .
        dockerfile: ./containers/phpfpm/Dockerfile

  ##
  # redis
  #
  train-redis:
    image: redis
    restart: unless-stopped
    env_file:
        - ./environment/redis.env
    volumes:
      - ./store/redis:/data

  ##
  # Front end web application
  #
  train-web:
    build:
        context: .
        dockerfile: ./containers/web/Dockerfile
    depends_on:
        - train-phpfpm

  train-mysql:
    image: mysql
    restart: unless-stopped
    container_name: train-mysql
    env_file:
        - ./environment/mysql.env
    volumes:
        - ./store/mysql:/var/lib/mysql
        - ./environment/mysql:/etc/mysql/conf.d
        - ./store/logs/mysql:/var/log/mysql
    ports:
        - 3306:3306
 ##
  # Front end web application
  #
  train-cron:
    build:
        context: .
        dockerfile: ./containers/scheduler/Dockerfile
